name: Pipeline Testes Automatizados Web Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


permissions:
  contents: read


jobs:
  automacao-web-ruby:
      timeout-minutes: 60
      runs-on: ubuntu-latest

      steps:
      - name: Passo 1 - Obter cópia código-fonte repositório
        uses: actions/checkout@v3
     
      - name: Passo 2 - Instalar ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
      
      - name: Passo 3 - Instalar dependências
        run:
            gem install capybara -v 3.38.0 cucumber -v 8.0.0 rspec -v 3.12.0 selenium-webdriver -v 4.6.1 site_prism -v 3.7.3 pry -v 0.14.1
        
      - name: Passo 4 - Executar testes e gerar relatório html 
        run:
            bundle exec cucumber -p ci
            
      - name: Passo 5 - Armazenar relatório html
        uses: actions/upload-artifact@v3
        # expressão condicional para que sempre seja executado independentemente dos resultados dos steps anteriores
        if: ${{ always() }}
        with: 
            name: reports
            path: ./reports/report.html
            retention-days: 30

